basePath: /v1
info:
  contact: {}
  description: Sketch API Server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Sketch API
  version: "1.0"
paths: {}
swagger: "2.0"
